# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/collabeditor
spring.datasource.username=collabuser
spring.datasource.password=collabpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7aa081468516903c37e1ac7d4e
app.jwt.expiration=86400000

jdoodle.client-id=3c55bc79f38d6607401713f9ff8f762c
jdoodle.client-secret=bd2e2f458732fc2f493386a6b54dc75aae5757ab679946b7b7c39ceffcf92137